// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwFB7Ym6oQ8WlWSN99ILzbo1CmcN7pSlM',
    appId: '1:558381784818:web:cf90590a52666d8409ba6b',
    messagingSenderId: '558381784818',
    projectId: 'mynotes-flutter-arjundev',
    authDomain: 'mynotes-flutter-arjundev.firebaseapp.com',
    storageBucket: 'mynotes-flutter-arjundev.appspot.com',
    measurementId: 'G-LG4LJGTMKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhUD48DpSNhIe8hbTlShYLdM3Z-jFjWJQ',
    appId: '1:558381784818:android:f412cfd5aa6a843409ba6b',
    messagingSenderId: '558381784818',
    projectId: 'mynotes-flutter-arjundev',
    storageBucket: 'mynotes-flutter-arjundev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTAjBX_1acA1Qh-WHnMWwCYwDbODpMKZo',
    appId: '1:558381784818:ios:096a402463e0e69409ba6b',
    messagingSenderId: '558381784818',
    projectId: 'mynotes-flutter-arjundev',
    storageBucket: 'mynotes-flutter-arjundev.appspot.com',
    iosClientId: '558381784818-m7gckp961fkagmam0r1tftclt20c2q24.apps.googleusercontent.com',
    iosBundleId: 'com.transform.mynotes',
  );
}
